# Generated by Django 2.2.16 on 2021-02-17 10:57
import logging

from django.db.models.deletion import CASCADE
from django.db import migrations, models

logger = logging.getLogger(__name__)

try:
    from geonode.layers.models import Layer
    logger.error("Linking LayerRNDT to Layer (<4.x) -- we're not supposed to be here!")
    # we're on branch 4.x and should not have the Layer class, anyway here it is
    # we can't iuse this model in 4.x bc class Layer does not exist anymore

    class Migration(migrations.Migration):
        dependencies = [
            ('rndt', '0001_initial'),
            ('layers', '24_initial')
        ]

        operations = [
            migrations.CreateModel(
                name='LayerRNDT',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('constraints_other', models.TextField(default=None, null=True)),
                    ('layer', models.OneToOneField(on_delete=CASCADE, to='layers.Layer')),
                ],
                options={
                    'verbose_name_plural': 'Layer RNDT',
                    'ordering': ('layer', 'constraints_other'),
                },
            ),
        ]

except ImportError:
    try:
        from geonode.layers.models import Dataset
        logger.debug("Deferring LayerRNDT creation on geonode>=4.x)")
        # when running on 4.x, we're going to deal with the RNDTLayer model in a brand new migration (0006)

        class Migration(migrations.Migration):
            dependencies = [('rndt', '0001_initial'), ]
            operations = [migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop)]

    except ImportError:
        raise Exception('Can not find base class for LayerRNDT')


