# Generated by Django 2.2.16 on 2021-02-24 18:05
import logging

from django.db import migrations, models

logger = logging.getLogger(__name__)

try:
    from geonode.layers.models import Layer
    logger.error("Linking LayerRNDT to Layer (<4.x) -- we're not supposed to be here!")
    class Migration(migrations.Migration):

        dependencies = [
            ('rndt', '0003_layerrndt'),
        ]

        operations = [
            migrations.AddField(
                model_name='layerrndt',
                name='resolution',
                field=models.FloatField(default=None, null=True),
            ),
        ]
except ImportError:
    try:
        from geonode.layers.models import Dataset
        logger.debug("Deferring LayerRNDT creation on geonode>=4.x)")
        # when running on 4.x, we're going to deal with the RNDTLayer model in a brand new migration (0006)

        class Migration(migrations.Migration):
            dependencies = [('rndt', '0003_layerrndt'),]
            operations = [migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop)]

    except ImportError:
        raise Exception('Can not find base class for LayerRNDT')

